name: stripcard
description: A new Flutter project.
publish_to: 'none'
version: 4.4.0+16

environment:
    sdk: ">=3.10.0 <4.4.0"
    flutter: ">=3.38.5 <4.0.0"
 
dependencies:
  flutter: 
    sdk: flutter       
  cupertino_icons: 1.0.8
  get: ^4.6.6
  flutter_screenutil: 5.9.3
  google_fonts: 6.2.1
  country_code_picker: 3.0.0
  material_design_icons_flutter: 7.0.7296
  get_storage: ^2.1.1
  logger: 2.4.0
  pin_code_fields: 8.0.1
  intl: 0.19.0
  image_picker: 1.1.2
  dotted_line: ^3.2.2
  flutter_svg: ^2.0.10+1
  percent_indicator: ^4.2.3
  # qr_code_scanner: ^1.0.1
  flip_card: ^0.7.0
  dotted_border: ^2.1.0
  carousel_slider: ^5.0.0
  dart_code_metrics: ^5.7.6
  connectivity_plus: 5.0.2
  flutter_spinkit: 5.2.1
  flutter_html: ^3.0.0-alpha.6
  flutter_inappwebview: ^6.0.0
  patterns_canvas: 0.5.0
  cached_network_image: ^3.3.1
  iconsax: ^0.0.8
  qr_flutter: ^4.1.0
  dropdown_button2: ^2.3.9
  restart_app: ^1.2.1
  r_dotted_line_border: ^0.1.1
  flutter_animate: ^4.5.0
  local_auth: ^2.3.0
  pusher_beams: ^1.1.1
  flutter_local_notifications: ^18.0.1
  firebase_core: ^3.6.0
  shimmer: ^3.0.0  # Check for the latest version
  rename_app: ^1.6.5



  http: any
  uuid: any
dependency_overrides:
  http: ^1.1.0
 
   
dev_dependencies:
  build_runner: ^2.3.3
   
  flutter_gen_runner:
  

  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  
  # flutter_app_name:
#   flutter_app_name: ^0.1.0

flutter_app_name:
   name: "EayoBet"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo/app_launcher.png"



flutter_gen:
  output: lib/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  
  fonts:
    - family: AgencyFB-Bold
      fonts:
        - asset: fonts/AgencyFB-Bold.ttf

  assets:
    - assets/card/
    - assets/clipart/
    - assets/clipart/Ellip.png
    - assets/clipart/Ellipse 1228.png
    - assets/clipart/Ellipse 1234.png
    - assets/clipart/Group 1321315496.png
    - assets/clipart/Group 1321315497 (2).png
    - assets/clipart/man.png
    - assets/clipart/mann.png
    - assets/clipart/men.png
    - assets/clipart/pp.png
    - assets/icon/
    - assets/logo/
    - assets/qr/